<?php

/**
 * @file
 * Functions to support theming in the bene child theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function bene_test_project_preprocess_html(array &$variables) {
}

/**
 * Implements hook_page_attachments_alter().
 */
function bene_test_project_page_attachments_alter(array &$page) {
}

/**
 * Implements hook_preprocess_page() for page.html.twig.
 */
function bene_test_project_preprocess_page(array &$variables) {
}

/**
 * Implements hook_preprocess_page_title() for page.html.twig.
 */
function bene_test_project_preprocess_page_title(&$variables) {
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function bene_test_project_theme_suggestions_block_alter(array &$suggestions, array $variables) {
}

/**
 * Implements hook_theme_suggestions_node_alter().
 */
function bene_test_project_theme_suggestions_node_alter(array &$suggestions, array $variables) {
}

/**
 * Implements hook_preprocess_HOOK() for Block document templates.
 */
function bene_test_project_preprocess_block(array &$variables) {
}

/**
 * Implements hook_theme_suggestions_field_alter().
 */
function bene_test_project_theme_suggestions_field_alter(array &$suggestions, array $variables) {
}

/**
 * Implements hook_theme_suggestions_field_alter().
 */
function bene_test_project_theme_suggestions_fieldset_alter(array &$suggestions, array $variables) {
}

/**
 * Implements hook_preprocess_node().
 */
function bene_test_project_preprocess_node(array &$variables) {
}

/**
 * Implements hook_theme_suggestions_views_view_alter().
 */
function bene_test_project_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
}

/**
 * Implements hook_preprocess_form().
 */
function bene_test_project_preprocess_form(array &$variables) {
}

/**
 * Implements hook_preprocess_select().
 */
function bene_test_project_preprocess_select(array &$variables) {
}

/**
 * Implements hook_preprocess_field().
 */
function bene_test_project_preprocess_field(array &$variables, $hook) {
}

/**
 * Implements hook_preprocess_details().
 */
function bene_test_project_preprocess_details(array &$variables) {
}

/**
 * Implements hook_theme_suggestions_details_alter().
 */
function bene_test_project_theme_suggestions_details_alter(array &$suggestions, array $variables) {
}

/**
 * Implements hook_preprocess_menu_local_task().
 */
function bene_test_project_preprocess_menu_local_task(array &$variables) {
}
